### PR TITLE
Updating Silverstripe logo to new logo

### PR DESCRIPTION
**Pull request by 3Dgoo**
This fixes issue #66
The logo was retrieved from https://www.silverstripe.com/assets/Brand-Guidelines/Silverstripe-logos-RGB.zip as linked to on the following page https://www.silverstripe.com/about-us/our-brand/

### CODE REVIEW

**Comment by 3Dgoo** [comment]
Hello. Is there anything I can do to help get this merged in?
Thank you.

**Comment by clarkepaul** [comment]
@3Dgoo Sorry to be a pain but we have a slightly different logo for the CMS which isn't in the pack yet. The only difference is "CMS" being included in the logo. I'll post it here shortly. 
Much appreciated, this change was coming up in the next months.

**Comment by 3Dgoo** [comment]
No problem, Paul. Sounds good. If you post the logo I'm happy to update the template with the correct SVG code.

**Comment by clarkepaul** [comment]
@3Dgoo Hopefully you can extract the SVG info to use, let me know if you need it somehow different.
[Silverstripe CMS logo.svg.zip](https://github.com/silverstripe/silverstripe-login-forms/files/5685749/Silverstripe.CMS.logo.svg.zip)

**Comment by 3Dgoo** [comment]
@clarkepaul I have updated the logo with the version you supplied. Please let me know if there are any problems with these changes.

**Comment by clarkepaul** [comment]
Awesome, I'll leave it with the devs to review and merge.

**Comment by emteknetnz** [comment]
**Before**

Normal mode
image

Dark mode

image

**Pull request**

Normal mode
image

Dark mode
image

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Generally looks good, though a couple of things:

a) Dark mode is not very legible, will need to get its colour closer to how it was previously - see screenshots I've attached on a comment

b) Will need to rebase to tip of 4 branch and rebuild css files to resolve merge conflicts

**Comment by clarkepaul** [comment]
I think using the SVG in dark mode we should go white (#FFF) with both the Silverstripe symbol and text if possible.

**Comment by 3Dgoo** [comment]
That is strange. I did put in the CSS for the logo displaying white in dark mode. Here is what it looks like for me from my testing:
image

If you check the changes in this PR, that code is in there.

I will look at rebasing this PR.

**Comment by 3Dgoo** [comment]
I have rebased this branch.

**Comment by emteknetnz** [comment]
OK seems good now

Normal mode
image

Dark mode
image

There's merge conflicts again due to another recently merged PR.  I'll sort this for you.

Thanks again for your contribution!

**Pull request merged**
